---
default: &DEFAULT
  :configure:
    :AWS_access_key_id: 'AKIAIAWV6JNCFMQED6YQ'
    :AWS_secret_key: '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'
    :response_group: 'Large'
    :country: 'us'
    :associate_tag: "from054-20"
  :query:
    :q: "%{q}"
    :options:
      :search_index: 'All'
      :response_group: 'Large, Accessories'
      :sort: "salesrank"


development:
  <<: *DEFAULT

test:
  <<: *DEFAULT
cucumber:
  <<: *DEFAULT

production:
  <<: *DEFAULT

